#!/usr/bin/with-contenv sh
echo "S6: Starting Remembrances-MCP..."
exec /usr/local/bin/remembrances-mcp --ollama-url http://localhost:11434 --surrealdb-url ws://localhost:8000 --ollama-model nomic-embed-text:latest --knowledge-base /knowledge-base --surrealdb-start-cmd "/usr/local/bin/surreal start --user root --pass root file:///data/database.db"